server:
  port: 8080

spring:
  application:
    name: myrzakhan-taskflow

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      pool-name: HikariPool
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    mongodb:
      uri: mongodb://admin:pass@localhost:27017/mongodb?authSource=admin

  rabbitmq:
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  valid:
    maxSize: 10485760
    allowedMimeTypes:
      - application/pdf
      - image/png
      - image/jpeg
