server:
  port: 8080

spring:
  application:
    name: myrzakhan-taskflow

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      pool-name: HikariPool
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    mongodb:
      uri: mongodb://admin:pass@localhost:27017/mongodb?authSource=admin

  rabbitmq:
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: taskflow-log-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  elasticsearch:
    uris: http://localhost:9200

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  valid:
    maxSize: 10485760
    allowedMimeTypes:
      - application/pdf
      - image/png
      - image/jpeg
