server:
  port: 8081

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5434/notification_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/master.yml

  rabbitmq:
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
