version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: event_consumer_service_mongodb
    environment:
        MONGO_INITDB_ROOT_DATABASE: mongodb
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27018:27017"
